name: Fraud Detection Engine

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code as soon as code is pushed to the develop branch
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python 3.12
      - name: Set up Python 3.12        
        uses: actions/setup-python@v4   # Use version 4 of the official "setup-python" action from GitHub's marketplace
        with:
          python-version: 3.12
          cache: 'pip'

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies    
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Display Python version
      - name: Display Python version  
        run: python -c "import sys; print(sys.version)"

      # Step 5: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 6: Build and push our Docker image to Docker Hub
      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/fraud-detection-api:latest
            ${{ secrets.DOCKER_USERNAME }}/streamlit-app:latest
          file: ./Dockerfile  # We expose both ports in a single file. single Dockerfile should be enough.

      # Step 7: SSH into our VM and deploy the latest Docker image using docker-compose
      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_HOST }}           # The public IP of your VM, stored as a secret
          username: ${{ secrets.VM_USERNAME }}   # Your VM's username
          key: ${{ secrets.SSH_PRIVATE_KEY }}    # Your SSH private key, stored as a secret
          script: |
            # Step 1: Install UFW if it's not already there
            sudo apt-get update
            sudo apt-get install -y ufw

            # Step 2: Configure and enable the firewall
            sudo ufw allow 22/tcp
            sudo ufw allow 8000/tcp
            sudo ufw allow 8501/tcp
            sudo ufw --force enable

             # Step 3: Install git and clone the repository
            sudo apt-get install -y git
            mkdir -p /home/saibharadwaj/app
            cd /home/saibharadwaj/app
            
            # Use 'git pull' if the repo already exists, otherwise 'git clone'
            if [ -d "Fraud_Detection" ]; then
                cd Fraud_Detection
                git pull
            else
                git clone --branch develop https://github.com/Bharadwaja92/Fraud_Detection.git
                cd Fraud_Detection
            fi

            # Step 4: Change to the app directory and deploy the containers
            sudo apt-get install -y docker-compose
            # mkdir -p /home/saibharadwaj/app
            # cd /home/saibharadwaj/app
            # cp ../docker-compose.yml .
            # cp ../start.sh .
            docker-compose up -d